### ISSUE TITLE
Feature: Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [zeldaret/oot#1077]
Hello, your repository is currently missing the Code of Conduct. If you would like to add that, then I can submit a PR for that. In that case, you need to provide me with a contact address (email address) that needs to be enlisted in the Code of Conduct. 

Thanks!

**Comment by superbonaci** [comment]
Do we need this?

**Comment by FahimFBA** [comment]
That depends. As I am seeing many repositories adding them to their repositories, I thought about asking that here as well.

**Comment by DimensionWarped** [comment]
This isn't a 'feature' request, it's more like a legal request and it's a pretty low priority one when you consider the code doesn't even have a license.

**Comment by FahimFBA** [comment]
That's also true!

**Comment by superbonaci** [comment]
The code of conduct is mainly for companies who are afraid of the press.

**Comment by AriaHiro64** [comment]
Im late to the party but with 10 years of experience modding this game I dont think there should be one. i would feel uncomfortable with the fact that smaller modding projects could get blacklisted by accident over an unnecessary code of conduct thus killing creativity. this is coming from a purely modding perspective. ive seen literally 3/4ths of rhdn get wiped due to a code of conduct.
