### ISSUE TITLE
 No such file or directory execinfo.h error when trying to install on Cygwin

### ISSUE THREAD

**Issue by ElBread3** [zeldaret/oot#1510]
Trying to set up the decomp with Cygwin according to the [instructions](https://github.com/zeldaret/oot/blob/master/docs/BUILDING_CYGWIN.md) but get this upon [4. Setup the ROM and build process](https://github.com/zeldaret/oot/blob/master/README.md#4-setup-the-rom-and-build-process)
Could somebody help me figure out what's wrong? Also I did [run ./fixle.sh](https://github.com/zeldaret/oot/blob/master/docs/BUILDING_CYGWIN.md#3-continue-with-linux-instructions) before building

$ make setup
make -C tools
make[1]: Entering directory '/home/elbread/oot/tools'
make -C ZAPD
make[2]: Entering directory '/home/elbread/oot/tools/ZAPD'
g++ -fpic -std=c++17 -Wall -Wextra -fno-omit-frame-pointer -DDEPRECATION_ON -O2 -I ZAPD -I lib/libgfxd -I lib/tinyxml2 -I ZAPDUtils -c -o build/ZAPD/CrashHandler.o ZAPD/CrashHandler.cpp
ZAPD/CrashHandler.cpp:19:10: fatal error: execinfo.h: No such file or directory
   19 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:116: build/ZAPD/CrashHandler.o] Error 1
make[2]: Leaving directory '/home/elbread/oot/tools/ZAPD'
make[1]: *** [Makefile:21: all] Error 2
make[1]: Leaving directory '/home/elbread/oot/tools'
make: *** [Makefile:265: setup] Error 2

**Comment by Dragorn421** [comment]
This is a "ZAPD can't be built under cygwin" issue

Leaving this open until I open a documented issue on the ZAPD repo

Partially resolved (workaround found) on discord
https://discord.com/channels/688807550715560050/688851337085190255/1092723409303121920

Message copypasted below

------

We can probably help you past this one obstacle but I wouldn't be surprised if there are more up ahead

This one obstacle may be overcome (probably) by dummifying zapd's crash handler, since it seems to use linux headers that your cygwin install doesn't provide
The simplest (and dirty) way seems to me to change that 1 to a 0 here
https://github.com/zeldaret/ZAPD/blob/master/ZAPD/CrashHandler.cpp#L5
```cpp
#define HAS_POSIX 1
```
You can find the ZAPD source in your oot repo clone under tools/ZAPD/
