### ISSUE TITLE
Generalizing Logic for Future OoT Editors

### ISSUE THREAD

**Issue by AlexanderGroeger** [zeldaret/oot#855]
Hi,

This is a project I'm quite interested in. I heard it is close to completion. I know that with a completed source code, the amount of rom hacks will explode exponentially. I haven't looked around, but I would imagine a new OoT editor with access to source code would be in demand soon. Assuming this is true, modifications to the source code to allow easy manipulation / additions to the game should be considered after the first completed release. 

I have one small example. See lines 53-56 in oot/src/code/z_game_over.c. There are checks for all possible swords, but with this hard coded, the addition of another sword equipment item could require making changes across several code files. One way generalize this is to define a constant variable tuple in one code file containing all the sword equipment items allowing other code to iterate through them or reference them by index. I would think it would be easier to add a new swords this way.

**Comment by gamestabled** [comment]
This project is a matching decompilation, which means that it produces a byte-for-byte identical ROM to the supported versions of OoT (which right now is just the MQ debug rom). The compiler is old and its output is very sensitive to small changes in the source code, which means that there is relatively little freedom to change the source and still end up with a matching ROM. For the most part, whenever you see strange coding choices, it is because that is how nintendo actually wrote it (or, its close enough to convince the compiler to generate the same code).

Making a version of OoT with code improvements would be a neat thing that could be done by using this project, but it is not the goal of this project itself.

**Comment by Zelllll** [comment]
To an extent though adding defines for things that might make sense for someone to modify makes sense though, but it seems that some people were against adding too many

**Comment by fig02** [comment]
Yeah as Gamestabled said, this project aims to write matching code, meaning it will contain any less than ideal programming patterns that Nintendo may have used.
When this project is finished, a third party can absolutely take this code and refactor it to their hearts content. But we will maintain matching in the main repo.

Closing this issue because it is out of scope of the project
